[general]
  import = ["~/.config/alacritty/theme/github_dark.toml"]

[window]
  dynamic_padding   = false
  decorations       = "buttonless"
  title             = ""
  dynamic_title     = false
  resize_increments = true
  option_as_alt     = "OnlyLeft"
  blur              = false
  padding           = { x = 8, y = 8 }

[font]
  normal = { family = "Geist Mono", style = "Regular" }
  size   = 14
  offset = { y = 4, x = 0 }

[terminal]
  shell = { program = "/opt/homebrew/bin/zsh", args = ["-l"] }

[cursor]
  style = { shape = "Beam", blinking = "On" }

[keyboard]
  bindings = [{ key = "T", mods = "Command", action = "CreateNewWindow" }]
