[[row]]
  ratio=11
  [[row.child]]
    type="cpu"
[[row]]
  ratio=14
  [[row.child]]
    ratio=4
    type="memory"
  [[row.child]]
    ratio=3
    [[row.child.child]]
      type="battery"
    [[row.child.child]]
      type="disk"
[[row]]
  ratio=10
  [[row.child]]
    type="network"
  [[row.child]]
    type="process"
