[formatting]
reorder_keys = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
align_comments = true
align_entries = true
indent_entries = true
indent_tables = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies"]

[rule.formatting]
reorder_keys = true
