[flags]
hide_time = true
hide_table_gap = true
regex = true
color = "default"

[[row]]
  ratio = 1
  [[row.child]]
    ratio = 2
    type = "cpu"
  [[row.child]]
    ratio = 2
    [[row.child.child]]
      ratio = 2
      type = "disk"
    [[row.child.child]]
      ratio = 1
      type = "batt"
  [[row.child]]
    ratio = 4
    type = "proc"

[processes]
columns = ["pid", "name", "cpu%", "mem%", "state", "time"]
