theme = "ayu_dark"

[editor]
line-number = "relative"
cursorline = true
continue-comments = true
preview-completion-insert = true
completion-replace = false
bufferline = 'multiple'
end-of-line-diagnostics = 'hint'

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-progress-messages = true
snippets = false

[editor.file-picker]
hidden = false
