[[language]]
  name             = "javascript"
  shebangs         = ["deno"]
  roots            = ["deno.json", "deno.jsonc"]
  file-types       = ["js"]
  language-servers = ["deno-lsp"]
  formatter = { command = 'biome', args = ["format", "--stdin-file-path", "buffer.js"] }
  auto-format      = true

[[language]]
  name             = "typescript"
  shebangs         = ["deno"]
  roots            = ["deno.json", "deno.jsonc"]
  file-types       = ["ts"]
  language-servers = ["deno-lsp"]
  formatter = { command = 'biome', args = ["format", "--stdin-file-path", "buffer.ts"] }
  auto-format      = true

[[language]]
  name             = "jsx"
  shebangs         = ["deno"]
  roots            = ["deno.json", "deno.jsonc"]
  file-types       = ["jsx"]
  language-servers = ["deno-lsp"]
  formatter = { command = 'biome', args = ["format", "--stdin-file-path", "buffer.jsx"] }
  auto-format      = true

[[language]]
  name             = "tsx"
  shebangs         = ["deno"]
  roots            = ["deno.json", "deno.jsonc"]
  file-types       = ["tsx"]
  language-servers = ["deno-lsp"]
  formatter = { command = 'biome', args = ["format", "--stdin-file-path", "buffer.tsx"] }
  auto-format      = true

[[language]]
  name             = "python"
  language-servers = ["pyright", "ruff"]
  auto-format      = true

[[language]]
  name        = "rust"
  auto-format = true

[[language]]
  name        = "toml"
  auto-format = true

[[language]]
  name        = "latex"
  auto-format = true


[language-server.deno-lsp]
  command     = "deno"
  args        = ["lsp"]
  environment = { NO_COLOR = "1" }

  [language-server.deno-lsp.config.deno]
    enable = true
    # unstable = true
    cacheOnSave = true
    # Enable completion of importing from registries
    # Enable completion of function calls
    suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }
    # suggest = { imports = { hosts = { "https://deno.land" = true, "https://crux.land" = true, "https://x.nest.land" = true } } }

[language-server.texlab.config.texlab]
  [language-server.texlab.config.texlab.build]
    onSave = true
    auxDirectory = "aux"
    logDirectory = "log"
    args = ["-pdf", "-interaction=nonstopmode", "-synctex=1", "%f", "-auxdir=aux"]

  [language-server.texlab.config.texlab.chktex]
    onOpenAndSave = true
    onEdit = true

  [language-server.texlab.config.texlab.latexindent]
    replacement = "-rv"



[language-server.pyright.config.python.analysis]
  typeCheckingMode = "basic"

[language-server.ruff]
  command = "ruff"
  args    = ["server"]


[language-server.rust-analyzer.config]
  [language-server.rust-analyzer.config.check]
    command = "clippy"

  [language-server.rust-analyzer.config.cargo]
    features = "all"
