[[row]]
  ratio=11
  [[row.child]]
    type="cpu"
[[row]]
    ratio=14
    [[row.child]]
      ratio=4
      type="mem"
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="batt"
      [[row.child.child]]
        type="disk"
[[row]]
  ratio=10
  [[row.child]]
    type="net"
  [[row.child]]
    type="proc"
