[colors.footer_bar]
  background = '#21262d'
  foreground = '#8b969e'

[colors.selection]
  background = '#0c2d6b'
  foreground = 'CellForeground'

[colors.primary]
  background = '#0d1117'
  foreground = '#c9d1d9'

# Normal colors
[colors.normal]
  black   = '#161b22'
  red     = '#f97583'
  green   = '#7ee787'
  yellow  = '#ffa657'
  blue    = '#79c0ff'
  magenta = '#d2a8ff'
  cyan    = '#a5d6ff'
  white   = '#6e7681'

# Bright colors
[colors.bright]
  black   = '#30363d'
  red     = '#f85149'
  green   = '#85e89d'
  yellow  = '#ffea7f'
  blue    = '#49a0ff'
  magenta = '#d2a8ff'
  cyan    = '#79e5ff'
  white   = '#fafbfc'

[[colors.indexed_colors]]
  index = 16
  color = '#d18616'

[[colors.indexed_colors]]
  index = 17
  color = '#f97583'
