[colors.footer_bar]
  background = '#21262d'
  foreground = '#8b969e'

[colors.selection]
  background = '#0c2d6b'
  foreground = 'CellForeground'

[colors.primary]
  background = '#0d1117'
  foreground = '#c9d1d9'

# Normal colors
[colors.normal]
  black   = '#161b22'
  red     = '#f85149'
  green   = '#56d364'
  yellow  = '#ffa657'
  blue    = '#a5d6ff'
  magenta = '#d2a8ff'
  cyan    = '#39c5cf'
  white   = '#8b949e'

# Bright colors
[colors.bright]
  black   = '#6e7681'
  red     = '#f97583'
  green   = '#85e89d'
  yellow  = '#ffea7f'
  blue    = '#a5d6ff'
  magenta = '#d2a8ff'
  cyan    = '#56d4dd'
  white   = '#fafbfc'

[[colors.indexed_colors]]
  index = 16
  color = '#d18616'

[[colors.indexed_colors]]
  index = 17
  color = '#f97583'
